on:
  pull_request:
jobs:
  mirror_repo:
    environment: GITLAB
    runs-on: self-hosted
    steps:
      - name: Sync Mirror Repository
        run: |
          #!/bin/bash
          curl --request POST --header "PRIVATE-TOKEN:${{ secrets.TOKEN }}" "${{ secrets.MIRROR_URL }}"
  trigger-ci:
    environment: GITLAB
    needs: mirror_repo
    runs-on: self-hosted
    steps:
      - name: Trigger Pipeline
        run: |
          #!/bin/bash
          # Get latest VLLM RELEASED VERSION from https://github.com/triton-inference-server/vllm_backend/releases
          TAG=$(curl https://api.github.com/repos/triton-inference-server/vllm_backend/releases/latest | grep -i "tag_name" | awk -F '"' '{print $4}')
          export TRITON_CONTAINER_VERSION=${TAG#v} # example: 24.06
          echo "TRITON_CONTAINER_VERSION = ${TRITON_CONTAINER_VERSION}"

          # Get latest VLLM RELEASED VERSION from https://github.com/vllm-project/vllm/releases
          TAG=$(curl https://api.github.com/repos/vllm-project/vllm/releases/latest | grep -i "tag_name" | awk -F '"' '{print $4}')
          export VLLM_VERSION=${TAG#v} # example: 0.5.3.post1
          echo "VLLM_VERSION = ${VLLM_VERSION}"

          curl --fail --request POST --form token=${{ secrets.PIPELINE_TOKEN }} -F ref=${GITHUB_HEAD_REF} -F variables[BUILD_OPTION]="BUILD_SOURCE" -F variables[TRITON_CONTAINER_VERSION]="TRITON_CONTAINER_VERSION" -F variables[VLLM_VERSION]="VLLM_VERSION" "${{ secrets.PIPELINE_URL }}"
