name: Validate Triton Pull request by running our change on latest vLLM release
on:
  pull_request:
jobs:
  mirror_repo:
    environment: GITLAB
    runs-on: self-hosted
    steps:
      - name: Sync Mirror Repository
        run: |
          #!/bin/bash
          curl --request POST --header "PRIVATE-TOKEN:${{ secrets.TOKEN }}" "${{ secrets.MIRROR_URL }}"
  trigger-ci:
    environment: GITLAB
    needs: mirror_repo
    runs-on: self-hosted
    steps:
      - name: Trigger Pipeline
        run: |
          #!/bin/bash
          # Get latest VLLM RELEASED VERSION from https://github.com/triton-inference-server/vllm_backend/releases
          TAG=$(curl https://api.github.com/repos/triton-inference-server/vllm_backend/releases/latest | grep -i "tag_name" | awk -F '"' '{print $4}')
          export TRITON_CONTAINER_VERSION=${TAG#v} # example: 24.08
          if [ -z "$TRITON_CONTAINER_VERSION" ]
            then
              echo "\$TRITON_CONTAINER_VERSION is NULL, setting it to 24.08"
              TRITON_CONTAINER_VERSION=24.10
            else
              echo "\$TRITON_CONTAINER_VERSION is NOT NULL"
          fi
          echo "TRITON_CONTAINER_VERSION = ${TRITON_CONTAINER_VERSION}"

          # Get latest VLLM RELEASED VERSION from https://github.com/vllm-project/vllm/releases
          TAG=$(curl https://api.github.com/repos/vllm-project/vllm/releases/latest | grep -i "tag_name" | awk -F '"' '{print $4}')
          export VLLM_VERSION=${TAG#v} # example: 0.5.5
          if [ -z "$VLLM_VERSION" ]
            then
              echo "\$VLLM_VERSION is NULL, setting it to 0.5.5"
              VLLM_VERSION=0.5.3.post1
            else
              echo "\$VLLM_VERSION is NOT NULL"
          fi
          echo "VLLM_VERSION = ${VLLM_VERSION}"

          curl --fail --request POST --form token=${{ secrets.PIPELINE_TOKEN }} -F ref=${GITHUB_HEAD_REF} -F variables[BUILD_OPTION]="BUILD_SOURCE" -F variables[TRITON_CONTAINER_VERSION]="${TRITON_CONTAINER_VERSION}" -F variables[VLLM_VERSION]="${VLLM_VERSION}" -F variables[TEST_OPTION]="ALL_TESTS" "${{ secrets.PIPELINE_URL }}"
