name: Validate latest vLLM release from https://github.com/vllm-project/vllm/releases against latest Triton release https://github.com/triton-inference-server/vllm_backend/releases
on:
  schedule:
    - cron: "30 09 */3 * *"
jobs:
  mirror_repo:
    environment: GITLAB
    runs-on: self-hosted
    steps:
      - name: Sync Mirror Repository
        run: |
          #!/bin/bash
          curl --request POST --header "PRIVATE-TOKEN:${{ secrets.TOKEN }}" "${{ secrets.MIRROR_URL }}"
  trigger-ci:
    environment: GITLAB
    needs: mirror_repo
    runs-on: self-hosted
    steps:
      - name: Trigger Pipeline
        run: |
          #!/bin/bash
          # Get latest VLLM RELEASED VERSION from https://github.com/triton-inference-server/vllm_backend/releases
          TAG=$(curl https://api.github.com/repos/triton-inference-server/vllm_backend/releases/latest | grep -i "tag_name" | awk -F '"' '{print $4}')
          export TRITON_CONTAINER_VERSION=${TAG#v} # example: 24.08
          
          # Get latest VLLM RELEASED VERSION from https://github.com/vllm-project/vllm/releases
          TAG=$(curl https://api.github.com/repos/vllm-project/vllm/releases/latest | grep -i "tag_name" | awk -F '"' '{print $4}')
          export VLLM_VERSION=${TAG#v} # example: 0.5.5
          echo "VLLM_VERSION = ${VLLM_VERSION}"
          
          if [ -z "$TRITON_CONTAINER_VERSION" || -z "$VLLM_VERSION"]
            then
              echo "Can't find latest Triton or vllm version.. Skipping CI run"
            else
              echo "TRITON_CONTAINER_VERSION = ${TRITON_CONTAINER_VERSION}"
              echo "VLLM_VERSION = ${VLLM_VERSION}"
              curl --fail --request POST --form token=${{ secrets.PIPELINE_TOKEN }} -F ref=${GITHUB_HEAD_REF} -F variables[BUILD_OPTION]="PULL_DOCKER" -F variables[TRITON_CONTAINER_VERSION]="${TRITON_CONTAINER_VERSION}" -F variables[VLLM_VERSION]="${VLLM_VERSION}" -F variables[TEST_OPTION]="ALL_TESTS" "${{ secrets.PIPELINE_URL }}"
          fi
          
